name: fmraipuromes
description: "A new Flutter project for Raipur home real state these is made by oraganzation focus media raipur"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
#version: 1.0.4+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  get_storage: ^2.1.1
  http: ^1.2.1
  shimmer: ^3.0.0
  permission_handler: ^11.0.0
  connectivity_plus: ^5.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  device_preview: ^1.1.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30
  google_nav_bar: ^5.0.6
  intl_phone_field: ^3.2.0
  carousel_slider: ^4.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.2.0
  flutter_widget_from_html: ^0.14.11
  dropdown_search: ^5.0.6
  gap: ^3.0.1
  animate_do: ^3.3.4
  lottie: ^3.1.0
  webview_flutter: ^4.7.0
  video_player: ^2.8.5
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  firebase_crashlytics: ^3.5.6
  youtube_player_flutter: ^8.1.2
  go_router: ^14.1.4
  intl: ^0.19.0
  syncfusion_flutter_sliders: ^25.2.7
  visibility_detector: ^0.4.0+2
  flutter_inappwebview: ^5.7.2+3
  flutter_file_downloader: ^2.0.0
  change_app_package_name: ^1.3.0
  get_ip_address: ^0.0.7
  flutter_launcher_icons: ^0.13.1
  app_tracking_transparency: ^2.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/png/
    - assets/svg/
    - assets/gif/


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/rprNewLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
