// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqpKfDKRR8KFJLZGb4I44aeTSsiKSmW80',
    appId: '1:1065514614314:web:d23159f5bd53bb1206cd53',
    messagingSenderId: '1065514614314',
    projectId: 'rprhomesapplemyhomes',
    authDomain: 'rprhomesapplemyhomes.firebaseapp.com',
    storageBucket: 'rprhomesapplemyhomes.appspot.com',
    measurementId: 'G-24MEKWFTGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfF5zTErXh8C5_h0_kjvKYV2DNn62X0Kc',
    appId: '1:1065514614314:android:c2c210cfdecc5a8206cd53',
    messagingSenderId: '1065514614314',
    projectId: 'rprhomesapplemyhomes',
    storageBucket: 'rprhomesapplemyhomes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0O7j8CAD72DE1g14U0nHQnqLXodDjwc',
    appId: '1:1065514614314:ios:2a5132aa452060f706cd53',
    messagingSenderId: '1065514614314',
    projectId: 'rprhomesapplemyhomes',
    storageBucket: 'rprhomesapplemyhomes.appspot.com',
    iosBundleId: 'com.rprHomesAppleMyHomes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0O7j8CAD72DE1g14U0nHQnqLXodDjwc',
    appId: '1:1065514614314:ios:b4f751f913dc3bfc06cd53',
    messagingSenderId: '1065514614314',
    projectId: 'rprhomesapplemyhomes',
    storageBucket: 'rprhomesapplemyhomes.appspot.com',
    iosBundleId: 'com.focusmedia.fmraipuromes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqpKfDKRR8KFJLZGb4I44aeTSsiKSmW80',
    appId: '1:1065514614314:web:2820a4860f5e10d006cd53',
    messagingSenderId: '1065514614314',
    projectId: 'rprhomesapplemyhomes',
    authDomain: 'rprhomesapplemyhomes.firebaseapp.com',
    storageBucket: 'rprhomesapplemyhomes.appspot.com',
    measurementId: 'G-7HF5DHSH13',
  );

}