// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDZjaS6AahpqPqoU-xIcIlxqL3b3o10o',
    appId: '1:510036102889:web:41f33979bf1a54ec68aa78',
    messagingSenderId: '510036102889',
    projectId: 'raipurhomenew',
    authDomain: 'raipurhomenew.firebaseapp.com',
    storageBucket: 'raipurhomenew.appspot.com',
    measurementId: 'G-HT8XLT6P02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9FXIdU6xEIi2x8kxyLO0p3b5MLfjLD0',
    appId: '1:510036102889:android:217f3b5432572df968aa78',
    messagingSenderId: '510036102889',
    projectId: 'raipurhomenew',
    storageBucket: 'raipurhomenew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1tBuBZWAO5PrgQv5KG3B3lKvKodYQ5w',
    appId: '1:510036102889:ios:d9788c66b631b06068aa78',
    messagingSenderId: '510036102889',
    projectId: 'raipurhomenew',
    storageBucket: 'raipurhomenew.appspot.com',
    androidClientId: '510036102889-82tphc7jol4bsuv4ocb6n0lrhjn2tp9h.apps.googleusercontent.com',
    iosClientId: '510036102889-j0a69fql84h5c045flgantmg52m0tpjm.apps.googleusercontent.com',
    iosBundleId: 'com.raipurHomes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1tBuBZWAO5PrgQv5KG3B3lKvKodYQ5w',
    appId: '1:510036102889:ios:bb9a18c0d6bfaeac68aa78',
    messagingSenderId: '510036102889',
    projectId: 'raipurhomenew',
    storageBucket: 'raipurhomenew.appspot.com',
    androidClientId: '510036102889-82tphc7jol4bsuv4ocb6n0lrhjn2tp9h.apps.googleusercontent.com',
    iosClientId: '510036102889-c5f048s8ansgga0oltbgs789ghpqsnhc.apps.googleusercontent.com',
    iosBundleId: 'com.focusmedia.fmraipuromes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYDZjaS6AahpqPqoU-xIcIlxqL3b3o10o',
    appId: '1:510036102889:web:ec5ad25c28e1ecac68aa78',
    messagingSenderId: '510036102889',
    projectId: 'raipurhomenew',
    authDomain: 'raipurhomenew.firebaseapp.com',
    storageBucket: 'raipurhomenew.appspot.com',
    measurementId: 'G-V1G10VL1P1',
  );

}