// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_gc8BcJO8pFQpQp-pcXK5i42MVgpjnw',
    appId: '1:632279561203:web:978cb3dc4544c10aab1886',
    messagingSenderId: '632279561203',
    projectId: 'raipurhomesapple-ffe83',
    authDomain: 'raipurhomesapple-ffe83.firebaseapp.com',
    storageBucket: 'raipurhomesapple-ffe83.appspot.com',
    measurementId: 'G-4FB2VHJK37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMW0_mSmZEmYN4ihMpWdwfdZNRxrX-xq8',
    appId: '1:632279561203:android:76be21609bd33a05ab1886',
    messagingSenderId: '632279561203',
    projectId: 'raipurhomesapple-ffe83',
    storageBucket: 'raipurhomesapple-ffe83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYc6FHrblmo4sjBL8Nv0LzJWbgYAiI_8',
    appId: '1:632279561203:ios:0e06d87057007f0cab1886',
    messagingSenderId: '632279561203',
    projectId: 'raipurhomesapple-ffe83',
    storageBucket: 'raipurhomesapple-ffe83.appspot.com',
    iosBundleId: 'com.raipurHomesApple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYc6FHrblmo4sjBL8Nv0LzJWbgYAiI_8',
    appId: '1:632279561203:ios:a9a7dea1c387870bab1886',
    messagingSenderId: '632279561203',
    projectId: 'raipurhomesapple-ffe83',
    storageBucket: 'raipurhomesapple-ffe83.appspot.com',
    iosBundleId: 'com.focusmedia.fmraipuromes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY_gc8BcJO8pFQpQp-pcXK5i42MVgpjnw',
    appId: '1:632279561203:web:1b465eef043f08b8ab1886',
    messagingSenderId: '632279561203',
    projectId: 'raipurhomesapple-ffe83',
    authDomain: 'raipurhomesapple-ffe83.firebaseapp.com',
    storageBucket: 'raipurhomesapple-ffe83.appspot.com',
    measurementId: 'G-985ED9Y7C2',
  );
}
